### PR TITLE
[WIP/RFC] Support for Spring 2

### PR DESCRIPTION
**Pull request by rom1dep**
Hoping that getting closer to upstream's Spring will give better support for native image compilation with GraalVM (ref: https://github.com/rstoyanchev/spr-issue-migration-test-2/issues/16756 ), here is my take on updating to latest Spring boot.

The project compiles fine, still work to do on the tests:
```
[INFO] 
[ERROR] Tests run: 101, Failures: 0, Errors: 51, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Airsonic ........................................... SUCCESS [  0.319 s]
[INFO] Subsonic REST API .................................. SUCCESS [  1.080 s]
[INFO] Sonos API .......................................... SUCCESS [  1.144 s]
[INFO] Airsonic Main ...................................... FAILURE [02:03 min]
```

### CODE REVIEW

**Comment by muff1nman** [comment]
Awesome to get an early start on this. We imagine this is something we should do the release after next.

**Comment by rom1dep** [comment]
@muff1nman : Thanks! I should have checked the PR list better because it appears that https://github.com/airsonic/airsonic/pull/850 is pretty much the same thing, probably cleaner :)

**Comment by jvoisin** [comment]
Shall we close this PR in favour of #850 then?

**Comment by jvoisin** [comment]
Superseded by @randomnicode's heap of PR :)

**Pull request closed without merging**
