### PR TITLE
WIP: Get rid of jackson2

### PR DESCRIPTION
**Pull request by jvoisin**
Jackson2 has a new critical vulnerability every
two weeks, it's awful. This commits replaces
it with javax.json instead.

### CODE REVIEW

**Comment by muff1nman** [comment]
Why? As long as we don't use polymorphic typing (we don't last I checked), we can ignore the gadget vulnerabilities.

**Comment by eharris** [comment]
I think the issue he's trying to address is that the build keeps breaking (seems like every couple weeks) due to new Jackson CVE's that we then have to manually exclude to get things working again.

**Comment by jvoisin** [comment]
Exactly what @eharris said

**Comment by fxthomas** [comment]
Isn't `javax.json` proposed for inclusion in the standard library modules? If we don't use the features Jackson provides, then we might as well use a more standard version. +1 from me!

**Comment by jvoisin** [comment]
Spring is depending on Jackson:

```
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.5.21.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.5.21.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.5.21.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.5.21.RELEASE:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-starter-logging:jar:1.5.21.RELEASE:compile
[INFO] |  |     +- org.slf4j:jcl-over-slf4j:jar:1.7.26:compile
[INFO] |  |     +- org.slf4j:jul-to-slf4j:jar:1.7.26:compile
[INFO] |  |     \- org.slf4j:log4j-over-slf4j:jar:1.7.26:compile
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.3.6.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.11.3:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.8.11:compile
```

Meh.

**Comment by jvoisin** [comment]
But, on the other hand, we can get rid of Jackson2 in our codebase as much as possible anyway.

**Comment by muff1nman** [comment]
But removing jackson in our code base then doesn't really solve the issue then. As we will still get project builds broken when jackson has a vuln.

**Comment by jvoisin** [comment]
Sure, but I would sleep better at night knowing that we're exposing less input to jackson.

**Comment by muff1nman** [comment]
Hm I dunno - jackson is pretty battle tested and very widespread. I sleep well at night knowing we're using the most proliferated json parsing library :smile:

**Comment by jvoisin** [comment]
But it has a [terrible security history]( https://www.cvedetails.com/vendor/15866/Fasterxml.html ), and they're using a blacklist approach to fix the deserialization issues :'(
As @fxthomas said, javax.json [seems to be]( https://mvnrepository.com/artifact/javax.json/javax.json-api ) in the stdlib.

**Comment by muff1nman** [comment]
And how many of those are gadget related? All of the ones I looked at..

**Pull request closed without merging**
