### PR TITLE
Update dependencies - DO NOT MERGE

### PR DESCRIPTION
**Pull request by randomnicode**
This PR is just testing grounds. Subsequent PRs will break up most of the changes here into more meaningful chunks.

Updates some libs.

The major ones are:
- JDOM -> JDOM2 (mostly import changes)
- EHCache 2.5 -> 3.2.3 (differences with tiered cache mechanisms, mostly localized to CacheFactory)
- Lucene 3 -> 7.5 (some api changes, mostly localized to SearchService)
- JFreeChart (some api changes)

### CODE REVIEW

**Comment by muff1nman** [comment]
Im a bit more nervous about this as some of these I either know will break stuff or has a good probability to break things. I.e. hsql dependecy change. 

With that said I think, I think we can still do this, but on these conditons:

1. We do it next release. This release has been postponed far too long and should only accept bug fixes at this point. 
2. We break these into smaller changes. I.e. do the lucene change in one pr, some of the smaller stuff grouped into another pr.

**Comment by jvoisin** [comment]
@randomnicode any chance you're still willing to work on this? I'd like to bump the dependencies too, maybe I can help.

**Comment by randomnicode** [comment]
@jvoisin  Sorry, I've been away. Thanks for continuing the work.

**Comment by jvoisin** [comment]
Glad to have you back, and happy to see that someone who actually knows what they're doing is taking this over!

**Pull request closed without merging**
