### PR TITLE
Fix #1077, spaces instead of coma in systemd lists

### LINKED ISSUE #1077: Sample systemd service file does not work
I'm running Ubuntu 18.04 with 
```
administrator@fserver:~$ systemctl --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

contrib/airsonic.service doesn't run out of the box because `SystemCallFilter` should be delimited with spaces. Not sure how it behaves on other systemd versions. Happy to open a PR

### PR DESCRIPTION
**Pull request by jooola**
From systemd man pages https://www.freedesktop.org/software/systemd/man/systemd.exec.html#System%20Call%20Filtering

### CODE REVIEW

**Comment by jvoisin** [comment]
I'll try to test this this week.

**Comment by fxthomas** [comment]
Appears to work for me!

**Comment by jvoisin** [comment]
Let's be wild and merge it then \o/

**Comment by jvoisin** [comment]
This fixes #1077.

**Pull request merged**
