### PR TITLE
Update Sonos wsdl file

### PR DESCRIPTION
**Pull request by jooola**
Updated Sonos wsdl file from https://musicpartners.sonos.com/sites/default/files/Sonos.wsdl

### CODE REVIEW

**Comment by jvoisin** [comment]
Marking every new method return null is something we're ok with?

**Comment by jooola** [comment]
I didn't think much about this, I saw some other methods returning null, or doing nothing. So I did the same with the new methods. I guess while we are not using them its fine. Not sexy but fine.

**Comment by jooola** [comment]
Ok just needs a little review

**Comment by fxthomas** [comment]
This looks okay to me, it does not touch a lot of things and appears clean. I don't have any way of testing it since I don't use Sonos, but let's merge it?

**Pull request merged**
