### PR TITLE
Bump jquery from 3.4.0 to 3.5.0

### PR DESCRIPTION
**Pull request by fxthomas**
See https://github.com/airsonic/airsonic/issues/1438#issuecomment-612991587, jQuery 3.5.0 has been released and this fixes a CVE.

### CODE REVIEW

**Comment by randomnicode** [comment]
I think you likely need to actually bump the script tag urls too in `jquery.jsp`, replacing just the library probably isn't enough.

**Comment by fxthomas** [comment]
Yeah, you're of course completely right, must have brain farted yesterday.

**Comment by fxthomas** [comment]
Saw no issues today during regular use. Anybody against merging?

**Comment by randomnicode** [comment]
lgtm 👍

**Pull request merged**
