### PR TITLE
Replace wz_tooltip.js with jquery-ui

### PR DESCRIPTION
**Pull request by jvoisin**
Since we're already using jquery-ui for other stuff, it makes sense to use it
for tooltips too, instead of using an old-school-written-in-2009 1300 lines
  steaming pile of javascript named wz_tooltip.js

### CODE REVIEW

**Comment by jvoisin** [comment]
This should close #1018.

**Comment by jvoisin** [comment]
This is currently blocked by #1001, because I have no clue on how to update the translations/texts, and I need to remove the `<p>…</p>` characters from the tooltips texts.

**Comment by muff1nman** [comment]
Is this one still blocked?

**Comment by jvoisin** [comment]
Yup, I need to find some time to edit the localizations :/

**Comment by jvoisin** [comment]
If anyone know some sed/awk, the question is: How to replace `helppopup.YYY.text=<p>XXX</p>` with `helppopup.YYY.text=XXX`. If nobody has a quick one-liner to drop, I'll allocate some time to write one at some point.

**Comment by fxthomas** [comment]
Something like (modifies files in-place):

```
find airsonic-main/src/main/resources/ -name 'ResourceBundle_*.properties' -print0 | xargs -0 sed -i 's/\(helppopup\..*\.text\)\s*=\s*<p>\(.*\)<\/p>/\1=\2/'
```

**Comment by jvoisin** [comment]
This is now ready to be reviewed'n'merged :)

**Pull request merged**
