### PR TITLE
Bump cucumber from 4.2.0 to 5.3.0

### PR DESCRIPTION
**Pull request by jvoisin**
- Bump the version of cucumber
- Remove the deprecated cucumber-parallel plugin

### CODE REVIEW

**Comment by jvoisin** [comment]
It seems that there is some snafu in generated code; no idea how to fix this :/

**Comment by fxthomas** [comment]
There is nothing in the Travis logs, did the integration tests pass?

**Comment by jvoisin** [comment]
I can see logs here

**Comment by fxthomas** [comment]
Ah, well, there are logs. Just not for the integration tests :wink: 

In `master` I can see these, but not in the test results for this branch:

image

**Comment by jvoisin** [comment]
[xxx]( https://travis-ci.org/airsonic/airsonic/jobs/650850430 )

They're here, but it indeed seems that something is wrong :/

**Comment by randomnicode** [comment]
Hey @jvoisin instead of a version bump, why not consider removing cucumber altogether?

**Comment by jvoisin** [comment]
Because I'm too lazy to migrate the tests to JUnit for now :/

**Comment by randomnicode** [comment]
:) Not lazy enough to bump the version and take a look at the associated issues.

If you must put in effort, go _all_ the way ;)

**Comment by tesshucom** [comment]
There seems to be some talk about build flow.
Someday it seems better to move the integration-test to another project....

In short, it's a good idea to erase lfs history from airsonic projects.
Since the quota is easily exceeded, it is troublesome to verify the technology with the clone.
This is not so good for airsonic...

**Comment by muff1nman** [comment]
> In short, it's a good idea to erase lfs history from airsonic projects.
Since the quota is easily exceeded, it is troublesome to verify the technology with the clone.
This is not so good for airsonic...

Let's not deviate from the topic at hand. We can open a separate issue to discuss our experience with lfs. 

> Hey @jvoisin instead of a version bump, why not consider removing cucumber altogether?

Why? There is value in a BDD testing that cannot be easily achieved with Junit.

**Comment by randomnicode** [comment]
> Let's not deviate from the topic at hand. We can open a separate issue to discuss our experience with lfs.

Probably should be a separate topic, I suspect it came up because the bulk of lfs is the test result fixtures used by cucumber.

>Why? There is value in a BDD testing that cannot be easily achieved with Junit.

I'm sorry, what exactly is the value it's providing?

What are you suggesting it's doing that failsafe can't do?

We don't even have test writer roles or business functions. There are no QAs.
We're not even properly using BDD, just incurring all the overhead to maintain it.

And not only that, it's even outdated and you can't even update it, which just points out it's actual negative value (penalty).

My suggestion is get rid of cucumber. Switch to Junit/failsafe for integration tests. All the verbiage or infrastructure setup and overhead of maintenance isn't necessary for what you're doing.

Stating something "provides value" is meaningless unless you can state what exactly is the value it's providing to this particular project. BDD isn't a tool necessary here. And you're not even using it.

**Comment by randomnicode** [comment]
@jvoisin https://github.com/airsonic/airsonic/issues/1240#issuecomment-595853829

**Comment by fxthomas** [comment]
Since #1619 has been merged, I guess this one is obsolete? I'll close it if you don't mind.

**Pull request closed without merging**
