### PR TITLE
Refactor jukebox service

### PR DESCRIPTION
**Pull request by biconou**
Refactor or jukeboxService to avoid if statements in PlayQueueService

### CODE REVIEW

**Comment by muff1nman** [comment]
I like the changes you did last time I looked through this. Do you mind if I squash this into one commit?

**Comment by biconou** [comment]
@muff1nman Thanks for reviewing this. 
I understand that you want to have something more clean in the git history. But it's not necessary you squash now. Indeed, this work is not over and this PR was only for discussion purpose. I'll finish this work, then I'll submit a new request quashing in one commit by myself. I'm not very familiar with these git advanced technics but I must learn and practice for more quality.
Do you agree ?

**Comment by muff1nman** [comment]
Okay, I just offered because I know its not going to be a simple squash operation due to the fact there are lots of merge commits. In general its best not to mix the two. Let me know if you need any help.

**Comment by biconou** [comment]
@muff1nman What I planned is : 
- take your pr/477 branch
- cherry pick my refactor commits
- continue the job
- commit
- rebase and squash all in one commit
- merge master
- push
- merge pr/477 branch on master 

Can you confirm it is a good way ?

**Comment by muff1nman** [comment]
@biconou Here is how I would go about it:

- take your pr/477 branch
- merge master to be up to date
- cherry pick my refactor commits
- continue the job
- commit
- ~rebase and squash all in one commit~
- merge master
- ~push~
- ~merge pr/477 branch on master~
- **Create a new branch based on master named squash**
- **Create a single commit with the combined diff of master..pr/477**
  - This can be done in several ways:
    - `git checkout -p`
    - https://stackoverflow.com/questions/6070179/switching-branches-without-touching-the-working-tree#answer-15993574
- **push squash branch and create a new pr**
- **merge squash branch into master**

**Pull request closed without merging**
