### PR TITLE
Upgrade cling UPnP/DLNA libs

### PR DESCRIPTION
**Pull request by randomnicode**
Upgrade cling libraries

### CODE REVIEW

**Comment by tesshucom** [comment]
#975
There was a degrate like this before.
Can this series of PR(Changing the port etc ...) be considered an update that resolves these issues?


If so, I am very happy:blush:

**Comment by randomnicode** [comment]
Hi @tesshucom thanks for pointing that out.
These PR series fix _a_ problem, though I don't know if it's _the_ problem.

I have no idea if that's the root cause because I don't know https://github.com/airsonic/airsonic/issues/975 was docker-related (which the port thing fixes)

Additionally https://github.com/airsonic/airsonic/issues/975 seems to indicate downgrading didn't help. Maybe @muff1nman can shed some light about what was happening?

**Comment by muff1nman** [comment]
Yep already tried updating these dependencies once. I don't remember exactly what broke before and I'm not sure that it was port related.

Whatever it is, this will need some serious testing before this goes in.

**Comment by tesshucom** [comment]
There are 3 classes of StreamClientConfigurationImpl implementation.
org.fourthline.cling.transport.impl, impl.apache, impl.jetty

Probably, the previous failure trigger was to replace to the apache configuration implementation.
apache was more strict with UDA, and certainly looked better if it could be replaced.
However, It returned to the original state without investigating because it was necessary to recover immediately.
Not only the settings, but also the library version was restored because we selected the safest option.

At that time, lib related to communication was updated at the same time with some trouble , so I felt that simultaneous verification was difficult.
This is the main reason for reverting.

Since randomnicode divides PR, I think that individual verification is possible.

@randomnicode
It may have been a side street about stream config, but the topic was that there was such a problem before.

**Comment by fxthomas** [comment]
Well, this will probably need a rebase. I personally can't test this (I don't use DLNA/UPnP) so I'll let you all handle this :wink:

**Comment by randomnicode** [comment]
Not maintining branches on this fork anymore so I'm just going to close this. Someone else can merge master onto these commits (or cherry-pick) and post a new PR if they wish

**Pull request closed without merging**
