### PR TITLE
Use less batching for certain SQL queries

### PR DESCRIPTION
**Pull request by randomnicode**
Effective diff: https://github.com/airsonic/airsonic/compare/ffd229e07d5387c0477de883478d0bbd6f1867e7...c2e3f0a

Some queries are doing things in batches of 1000, which means multiple connections are being opened to the DB for no apparent reason. These are costing multiple round-trip times, when a single query should suffice.

This replaces these batch loops with a single query where needed.

### CODE REVIEW

**Comment by jvoisin** [comment]
Why the fuck where those queries done in a `for` loop in the first place :/
The effective diff looks good, trivial and useful to me, but I guess that we'll have to merge #1377 first.

**Comment by randomnicode** [comment]
Don't know. Maybe Sindre thought it'd be faster with a file-based DB

**Comment by fxthomas** [comment]
Looks good to me too.

Minor nitpick: can we get away with removing the min/max id checks? They appear useless for what we're doing here.

**Comment by randomnicode** [comment]
Good point, done here: https://github.com/airsonic-advanced/airsonic-advanced/pull/28 with an additional commit, feel free to backport with the additional commit.

**Comment by tesshucom** [comment]
I also noticed when I copied it, but left it as it was.

Because it predicted the existence of concerns pointed out in https://github.com/airsonic-advanced/airsonic-advanced/pull/28.

In fact, the optimal solution depends on the target DB implementation.

**Comment by tesshucom** [comment]
I also noticed when I copied it (to the expunge method), but left it as it was.

The code reminds me of some concerns.
This concern seems to have already been explained at https://github.com/airsonic-advanced/airsonic-advanced/pull/28.

In fact, the optimal solution depends on the target DB implementation and amount of data.

**Comment by randomnicode** [comment]
I agree with concerns voiced by @eharris and @tesshucom. However, the current implementation is too inflexible and thus slow for most people. The correct implementation is, as @tesshucom pointed out, data dependent, with this PR being the correct implementation for large to small libraries and a variant of the existing implementation as the correct thing to do for massive libraries. (Additionally, type of db also likely matters.)

I concur with the approach outlined by @eharris that we should make this configurable so folks are able to play around to find the "right" amount of aggressiveness for their own use case with some default built in to suit most folks. I'll likely post a followup PR if someone doesn't beat me to it.

**Comment by randomnicode** [comment]
Follow up (backend + UI) posted here: https://github.com/airsonic-advanced/airsonic-advanced/pull/31
Along with some useful indices here: https://github.com/airsonic-advanced/airsonic-advanced/pull/32

Feel free to backport

**Pull request closed without merging**
