### PR TITLE
Default server.use-forward-headers=true

### PR DESCRIPTION
**Pull request by tari**
Fix for #594. I'm not certain what this will do if not behind a proxy, but don't think it should be an issue. May be worth testing though.

### CODE REVIEW

**Comment by muff1nman** [comment]
If this is really needed, it should be configured by default in the shipped `application.properties`. I'm still looking to understand why explicit configuration of that setting is needed though.

**Comment by muff1nman** [comment]
This should not be needed. I tested httpd with ssl and it seems to be working just fine. No mixed content errors or anything.

```
Listen 443 https
<VirtualHost *:443>
        SSLEngine on
        SSLCertificateFile "/etc/httpd/conf.d/test.crt"
        SSLCertificateKeyFile "/etc/httpd/conf.d/test.key"
        ProxyRequests off
        ProxyPreserveHost on
        SSLProxyEngine on

        RequestHeader set X-Forwarded-Proto "https"

        ProxyPass "/airsonic" "http://localhost:8080/airsonic"
        ProxyPassReverse "/airsonic" "http://localhost:8080/airsonic"
</VirtualHost>
```

Is your airsonic actually localhost or did you change it when posting on #594

**Comment by tari** [comment]
It is actually localhost; I'm not sure why ProxyPassReverse alone isn't sufficient, but it seems like I'm not the only one with that problem so it's probably not just weird configuration on my end.

I was hesitant to set this in application.properties because it may do the wrong thing in some situations- if not behind a proxy a client may be able to set those headers directly and cause wrong redirects (which may not be a problem if it's not a security issue).

**Comment by muff1nman** [comment]
Can you please create clear reproduce steps for #594? I have yet to see a case where there was an actual issue with the proxies that was not a configuration issue.

**Comment by jolny** [comment]
Without the "RequestHeader set X-Forwarded-Proto "https"" line, I got these mixed content errors.
But you mean the above configuration, without use-forward-headers, should suffice?

**Comment by synchrone** [comment]
@muff1nman I have a guess that maybe you're testing on localhost domain, for which the browser ignores https -> http redirect in an iframe. I'm trying to deploy standalone Airsonic behind an nginx I don't control

@tari normally X-Forwarded headers are only respected when set by a whiitelisted server (like nginx [set_real_ip_from](http://nginx.org/en/docs/http/ngx_http_realip_module.html#set_real_ip_from), and any security implications only make sense for X-Forwarded-For anyway (since that's what apps trust to be the correct origin ip)

People have been fighting over this simple servlet container configuration option since [way back](https://github.com/airsonic/airsonic/commit/4d6ca84ec6b4e4f4503cb21f0c1fc10145a55695#diff-a9a452901374e197ac59af71f41ac4e1R132), often implementing horrible hacks (like this one in HAProxy, while it was only 1 config option to just make Spring+Tomcat/Jetty to properly implement HTTP Proxy protocol.

**Comment by tari** [comment]
@muff1nman I did some more investigation and it's dependent on `ProxyPreserveHost` being enabled. More detail in [my comment there](https://github.com/airsonic/airsonic/issues/594#issuecomment-348645518); not using this setting but still honoring X-Forwarded headers in other contexts seems inconsistent and confusing, supported by the observation that I'm not the only user to experience this problem.

**Comment by muff1nman** [comment]
@synchrone That's helpful to know. Yes I have been testing on a single host. I'm just trying to get this reproduced so I can follow along with the pains that are being experienced. Let's continue the discussion in #594 and leave this pr alone for a minute.

**Comment by muff1nman** [comment]
As per my comment in https://github.com/airsonic/airsonic/issues/594#issuecomment-352199029 this shouldn't be needed anymore as long as we stick with Tomcat.

**Comment by jooola** [comment]
Using this with standalone behind haproxy fixed the few broken links ( in the right pane for the currenlty played songs and the stream url finally has a HTTPS )

**Pull request closed without merging**
